--- 
title: "UBCO Ecology of Campus Guide"
author: "Jordan Katchen and Ian Sanga"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
link-citations: yes
github-repo: rstudio/bookdown-demo
output: 
  bookdown::gitbook:
    includes:
      in_header: google_analytics.html
---

# Welcome

This is the online home of UBCO’s campus ecology guide created by Ian Sanga and Jordan Katchen.

Campus life is busy! With projects, midterms, clubs, and job applications, it can be hard to take a minute to reflect on the community we call UBCO. But if you’re lucky enough to have a break between classes or decide to enjoy the refreshing spring weather while having lunch, take a look around to see the rich biodiversity surrounding you. We built this website to ease the community into the basic ecology of campus by highlighting some of the interesting species you’ll likely see around. Campus is home to many interesting members of the local ecosystem, from native flora and fauna that are integral parts of the Okanagan to invasive guests like the European Mantis that disrupt natural ecosystems.

---

This webpage was built using the bookdown R package. Source code for this book can be found on [GitHub](https://github.com/JordanK200/UBCO_ecology_guide).

Feedback can be provided on our [GitHub](https://github.com/JordanK200/UBCO_ecology_guide/issues). All feedback and comments are greatly appreciated!

The data for this project has been sourced from [iNaturalist](https://www.inaturalist.org/). A special thanks to the members of [UBC Okanagan BioInventory](https://www.inaturalist.org/projects/ubc-okanagan-bioinventory) who provided many of the locations and photos included in this assignment. All attributions are provided alongside associated images.

This project was created for the UBCO course *BIOL420N: Science in Digital Media*. Shout out to Dr. Robin Young for offering such a fun and creative course!

This work is licensed under a [Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/).

A map of all location data is provided below:

<div class="map-responsive">

<iframe src="https://www.google.com/maps/d/embed?mid=11PYhsV-ntT5O_CSmY8aGnT9pU8gHFqo&ehbc=2E312F" width="600" height="800" frameborder="0" style="border:0" allowfullscreen></iframe>

</div>